### PR TITLE
reduce the network usage post

### PR DESCRIPTION
**Pull request by b00f**
The post explains how to reduce the network usage in Pactus

### CODE REVIEW

**Review by Mr-HoDL58 — COMMENTED** [review]
All looks good.

**Comment by Ja7ad** [comment]
```shell
./website/_i18n/ar/user-guides/reduce-network/index.md:15: MD013 Line length
./website/_i18n/ar/user-guides/reduce-network/index.md:20: MD013 Line length
./website/_i18n/ar/user-guides/reduce-network/index.md:25: MD013 Line length
./website/_i18n/ar/user-guides/reduce-network/index.md:29: MD013 Line length
./website/_i18n/en/user-guides/reduce-network/index.md:15: MD013 Line length
./website/_i18n/en/user-guides/reduce-network/index.md:20: MD013 Line length
./website/_i18n/en/user-guides/reduce-network/index.md:25: MD013 Line length
./website/_i18n/en/user-guides/reduce-network/index.md:29: MD013 Line length
./website/_i18n/zh/user-guides/reduce-network/index.md:15: MD013 Line length
./website/_i18n/zh/user-guides/reduce-network/index.md:20: MD013 Line length
./website/_i18n/zh/user-guides/reduce-network/index.md:25: MD013 Line length
./website/_i18n/zh/user-guides/reduce-network/index.md:29: MD013 Line length
```

Please fix this.

**Comment by b00f** [comment]
@Ja7ad @Mr-HoDL58 the linting issues are fixed

**Review by Ja7ad — APPROVED** [review]

**Comment by Ja7ad** [comment]
@b00f thank you

**Pull request merged**
