### PR TITLE
feat: add SSPoS in DOCs

### PR DESCRIPTION
**Pull request by kehiy**
I think we need to use `SSPoS` word in our DOCs
it's much better.

### CODE REVIEW

**Comment by kehiy** [comment]
@b00f can you have a review?

**Review by b00f — APPROVED** [review]

**Comment by b00f** [comment]
@kehiy better to not rename the file. We have broken links

**Comment by kehiy** [comment]
@b00f okay

**Comment by kehiy** [comment]
@b00f we still have problems?!?!

**Pull request merged**
