### PR TITLE
fix: partner logo and address

### PR DESCRIPTION
**Pull request by Ja7ad**

### CODE REVIEW

**Comment by b00f** [comment]
@Ja7ad please add it using partner template: https://github.com/pactus-project/pactus.org/blob/main/website/assets/images/partners/partners_logo_template.psd

**Comment by Ja7ad** [comment]
> @Ja7ad please add it using partner template: https://github.com/pactus-project/pactus.org/blob/main/website/assets/images/partners/partners_logo_template.psd

done

**Comment by b00f** [comment]
@Ja7ad waiting for this PR

**Comment by Ja7ad** [comment]
@Mr-HoDL58 Please check partner image for merge

**Comment by b00f** [comment]
@Ja7ad Please fix the image. We can't do it. The template is there. Make sure it is not transparent.

**Pull request closed without merging**
